services:
  db:
    image: mariadb:10.11
    container_name: servitec_db
    command:
      - "--lower_case_table_names=1" # evita problemas de mayúsculas/minúsculas en nombres de tablas
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    build: .
    container_name: servitec_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Datasource (override a application.yml/properties)
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      # JWT
      JWT_SECRET: ${JWT_SECRET}
      # Puerto de la app (opcional; por defecto 8090)
      SERVER_PORT: ${SERVER_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8090:8090"
    volumes:
      # Persistir y compartir subidas (efirma/certificacion)
      - ./uploads:/app/uploads

volumes:
  db_data:
