server:
  port: ${SERVER_PORT:8090}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://db:3306/ServitecDB}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:MSqlDB}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:change-me}
  expirationDateInMs: ${JWT_EXPIRATION:3600}
  refreshExpirationDateInMs: ${JWT_REFRESH_EXPIRATION:900}

logging:
  level:
    root: INFO

