server:
  port: ${SERVER_PORT:8090}

# Set here configurations for the database connection
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/springsecurity}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:MSqlDB}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

# LOGGING LEVEL
logging:
  level:
    root: INFO

# JWT
jwt:
  secret: ${JWT_SECRET:change-me}
  expirationDateInMs: ${JWT_EXPIRATION:3600}
  refreshExpirationDateInMs: ${JWT_REFRESH_EXPIRATION:900}
